version: '3'

services:
  pretix:
    image: 'pretix/standalone:stable'
    container_name: pretix_app
    restart: always 
    depends_on:
      - postgres
      - pgadmin
      - redis
    volumes:
      - ./pretix/data:/data
      - ./pretix/conf:/etc/pretix
    ports:
      - 80:80
    networks:
      - stack_network

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - db_volume:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - stack_network
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - stack_network 
    restart: unless-stopped
  redis:
    image: redis:latest
    restart: always
    networks:
      - stack_network

networks:
  stack_network:
    driver: bridge

volumes:
  db_volume:
    external: false